version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  manager:
    build:
      context: "./manager"
      dockerfile: "dockerfile_1"
    depends_on:
      - db
  amdiner:
    image: adminer
    ports:
      - 1234:8080
    depends_on:
      - db
